server:
  port: 8200

spring:
  application:
    name: com.touchbiz.starter.example
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true

  messages:
    basename: i18n/messages
    cache-second: 3600
    encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    max-active: 300
    password:
    timeout: 500
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 500
        min-idle: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'

#feign 配置
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 15000
#        readTimeout: 15000
#        loggerLevel: full


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy:  SEMAPHORE
          thread:
            timeoutInMilliseconds: 15000


logging:
  config: classpath:logback-spring.xml

knife4j:
  enable: true
  title: Standrad Demo



ribbon:
  okhttp:
    enabled: true
  http:
    client:
      enabled: false

feign:
  httpclient:
    enabled: false
    max-connections: 500
  okhttp:
    enabled: true



